site_name: libops
site_url: https://docs.libops.io/

repo_url: https://github.com/libops/docs
edit_uri: 'edit/main/docs/'

theme: material
plugins:
  - search
  - social
  - tags

nav:
  - Home: index.md
  - Development:
    - Overview: development/index.md
    - libops CLI: development/cli.md
    - libops YML: development/yml.md
    - Metrics: development/metrics.md
  - Site:
    - Overview: 'site/index.md'
    - Login: 'site/login.md'
