name: build-push-deploy
on:
  push:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-push:
    uses: libops/actions/.github/workflows/build-push.yml@main
    with:
      image: "shared/docs"
    permissions:
      contents: read
      id-token: write
    secrets: inherit
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs: [build-push]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955' # v4

    - uses: 'google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed' # v2
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
        service_account: ${{ secrets.GSA }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@251330ba9a8a34bfbc1622895f42e1d53fd14522' # v2
      with:
        service: 'docs-production'
        image: 'us-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/shared/docs:main'
        project_id: ${{ secrets.GCLOUD_CR_PROJECT }}
        region: ${{ secrets.GCLOUD_REGION }}
